id: P001770
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4608
  title: སྔགས་མང་ཞིབ་འཇུག ༼༦༽
  author: ''
  volumes:
    3ce35595fcb745e2bbd1e9861eadd095:
      image_group_id: I1PD27267
      title: ''
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
